version: 2.1
orbs:
  node: circleci/node@4.9.0
jobs:
  build:
    executor:
      name: node/default
      tag: '16'
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: sudo npm i -g codecov node-gyp && npm ci

      - run:
          name: lint
          command: npm run lint

      - run:
          name: test
          command: npm test && codecov

      - run:
          name: code-coverage
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
